### ISSUE TITLE
Add a customised variable

### ISSUE THREAD

**Issue by bixuanzju** [syohex/emacs-quickrun#44]
I have a toy programming language that I want to just use the source file name instead of copying to temporary file first after invoking `quickrun` (like the case of Java language).

Could it be possible to provide such customised variable that users can specify for which `quickrun` will not generate a temporary file?

**Comment by syohex** [comment]
> Could it be possible to provide such customised variable that users can specify for which quickrun will not generate a temporary file?

Yes. please wait, I'll implement such feature in this weekend.

**Comment by syohex** [comment]
It is better to specify whether or not using temporary file.
We can write new command setting as below. How about this ?

```lisp
(quickrun-add-command "your_program_interpreter"
                      '((:exec . ("some_interpreter run %s"))
                        (:tempfile . nil)))
```

**Comment by bixuanzju** [comment]
Exactly what I wanted, Thanks!

**Comment by syohex** [comment]
Please wait until merging.

**Comment by syohex** [comment]
@bixuanzju I have merged #45. Please check latest version.

**Comment by bixuanzju** [comment]
Does `not using temporary file` imply that `quickrun-region` is no longer supported?

**Comment by syohex** [comment]
> Does not using temporary file imply that quickrun-region is no longer supported?

Yes.

**Comment by scaramouche1** [comment]
It seems there's a problem with `:tempfile`.  I set it to nil, but a tempfile is still being used.  I just updated quickrun from Melpa.

I am calling quickrun-compile-only, using the following variables (set as local variables within a markdown file I want to compile):

**Comment by syohex** [comment]
Thanks for information. I'll check.

**Comment by syohex** [comment]
Condition of whether using temporary file is wrong.
I'll fix later.

**Comment by syohex** [comment]
@scaramouche1 Would you check latest version ?

**Comment by scaramouche1** [comment]
It's working!  Many thanks for the fast response!
