### ISSUE TITLE
quickrun-shell should switch cursor to shell buffer by default

### ISSUE THREAD

**Issue by tuhdo** [syohex/emacs-quickrun#55]
For example, I have an interactive C++ program that requires input. For this reason, I use the `quickrun-shell` command over the `quickrun` command. But, the cursor is on `*quickrun*` by default and I have to switch to `*eshell*` buffer manually. Also, I have to quit the eshell before quitting the `*quickrun*` buffer because if I press `q` to quit `*quickrun*` buffer first, quitting `*eshell*` bufferr gives error, so it's better for the cursor on shell buffer by default.

**Comment by syohex** [comment]
I fixed at #56. Please check latest version.

**Comment by tuhdo** [comment]
Sorry about late response. It was fixed. Thank you.
