### ISSUE TITLE
no need to recenter the quickrun output buffer when using `quickrun-replace-region``

### ISSUE THREAD

**Issue by Lompik** [syohex/emacs-quickrun#57]
using `quickrun-replace-region` throws the error : `Wrong type argument: window-live-p, nil` (region get replaced as expected). For example on this python code : `print("hello")` 
I have solve the issue with : 

    *** a/quickrun.el
    --- b/quickrun.el
    ***************
    *** 868,875 ****
                           (message "Failed: Exit Status=%d" exit-status))
                       (quickrun/apply-outputter outputter-func)
                       (run-hooks 'quickrun-after-run-hook))
    !                (cond ((> scroll-conservatively 0) (quickrun/recenter nil))
    !                      ((/= scroll-step 0) (quickrun/recenter -1)))
                     (quickrun/remove-temp-files)))))))

      ;;
    --- 868,876 ----
                           (message "Failed: Exit Status=%d" exit-status))
                       (quickrun/apply-outputter outputter-func)
                       (run-hooks 'quickrun-after-run-hook))
    !                (unless (string= outputter-func 'replace)
    !                  (cond ((> scroll-conservatively 0) (quickrun/recenter nil))
    !                        ((/= scroll-step 0) (quickrun/recenter -1))))
                     (quickrun/remove-temp-files)))))))

      ;;

Regards
lompik

**Comment by syohex** [comment]
Thanks for report.
I applied your change at #58. Please check latest version.

**Comment by syohex** [comment]
Please reopen if you still have this issue.
