### ISSUE TITLE
quickrun scrolls the code buffer to the bottom

### ISSUE THREAD

**Issue by tuhdo** [syohex/emacs-quickrun#59]
When I run quickrun with eshell, and abort the program before it finishes with `C-c C-c`, quickrun always scrolls my code buffer to the bottom, which is annoying.

To reproduce:
- Set quickrun to use Eshell.
- Run a program with some input i.e. scanf
- When you are asked for input, `C-c C-c` to abort the program and press `q` to quit Eshell.
- Point is at the bottom in code buffer.

**Comment by syohex** [comment]
I have fixed at #61. Please check latest version.

**Comment by syohex** [comment]
Please reopen if you still have this issue.
