### ISSUE TITLE
quickrun quits eshell immediately when pressing any key

### ISSUE THREAD

**Issue by tuhdo** [syohex/emacs-quickrun#60]
To reproduce:

- Run a program using Eshell.
- Press any key and `quickrun` exits Eshell immediately, prevent users from copying the output.

**Comment by syohex** [comment]
I fixed at #62. Please check latest version.

**Comment by tuhdo** [comment]
It fixed the problem but now there's another problem: I can no longer press `q` to quit the window.

**Comment by syohex** [comment]
I fixed at #63 . Please check latest version.

**Comment by syohex** [comment]
Please reopen if you still have this issue.
