### ISSUE TITLE
add support for HTML source code file.

### ISSUE THREAD

**Issue by stardiviner** [syohex/emacs-quickrun#69]
Let it opened by system default associated external program.
In Linux, it is runned by a command (I forget what it is... :( )

**Comment by syohex** [comment]
Open by web browser ?

**Comment by stardiviner** [comment]
Yes. system like Gnome will use `gconf` etc bind file extensions `.html` to associated programs.
Or use Emacs internal default open browser list.

**Comment by syohex** [comment]
Is `browse-url-of-file` enough for your purpose ?

**Comment by stardiviner** [comment]
Yes, that's great!
