### ISSUE TITLE
fail to display ANSI color codes

### ISSUE THREAD

**Issue by murasesyuka** [syohex/emacs-quickrun#70]
ansi color code is not support?

I run quickrun, c++ compile error log on **quickrun** buffer is

```
[1mqr_3031oQQ.cpp:5:1: [0m[0;1;31merror: [0m[1mC++ requires a type specifier for all declarations[0m
a;
[0;1;32m^
[0m1 error generated.
```

I expect error log, as follows

```
Welcome to the Emacs shell

$ 
$ clang++ -O3 -std=c++1z xorshift.cpp 
xorshift.cpp:5:1: error: C++ requires a type specifier for all declarations
a;
^
```

# env

I use quickrun version is 

``` 
;; Package-Version: 20151203.2152
;; Version: 2.2.6
```

emacs and gcc version is

```shell
$ emacs --version
GNU Emacs 24.5.1
...
$ gcc --version
gcc (Debian 5.3.1-5) 5.3.1 20160101
...
```

**Comment by syohex** [comment]
> ansi color code is not support?

quickrun.el supports ANSI color escape. You can see this `sample/sample_color.pl`. Here is screenshot of it.

![test](https://cloud.githubusercontent.com/assets/554281/12216297/ddf6aaa4-b71f-11e5-9e50-c4e4d33d21f7.png)

By the way, GCC or clang does not generate ANSI color escape if output is not tty. So I cannot got your result.

I can got ANSI escape sequence on terminal emulator as below.

![test1](https://cloud.githubusercontent.com/assets/554281/12216304/2dbce3b4-b720-11e5-8831-9ad50cb8fe10.png)

But I cannot get it on Emacs as below.

![test2](https://cloud.githubusercontent.com/assets/554281/12216307/3a625ca2-b720-11e5-81c2-dc517f657d17.png)

**Comment by murasesyuka** [comment]
thx for reply.

> quickrun.el supports ANSI color escape. You can see this sample/sample_color.pl. Here is screenshot of it.

I try and it is same output result.

> By the way, GCC or clang does not generate ANSI color escape if output is not tty. So I cannot got your result.

Oh, it ok. I checking My Enviroment.

**Comment by murasesyuka** [comment]
emacs reinstall. and fix problem. it sorry..
