### ISSUE TITLE
In nim, quickrun doesn't fail if it needed

### ISSUE THREAD

**Issue by yuutayamada** [syohex/emacs-quickrun#71]
I tried emacs -Q (with master branch emacs)
and I checked quickrun.el and quickrun.elc (updated today)

In following file named array.nim, the compile process should fail
because of using same file name and type, but M-x quickrun success to compile.
(Nim recognizes file name as module name, so. [about module)](http://nim-lang.org/docs/manual.html#modules)

array.nim
```nim
var a: array[0..2, int] = [1, 2, 3]
for ary in a:
  echo ary
```

from M-x quickrun:
-> 1, 2, 3

from shell:
```sh
$ nim compile --run --verbosity:0 array.nim # <- actually I tried absolute path
array.nim(1, 8) Error: ambiguous identifier: 'array' -- use a qualifier
```

nim version:
```sh
$ nim --version
Nim Compiler Version 0.13.1 (2016-02-01) [Linux: amd64]
Copyright (c) 2006-2016 by Andreas Rumpf

git hash: ac1e7a245093bb28a1a366f1e169ab50e6660c94
active boot switches: -d:release

**Comment by syohex** [comment]
Thanks for reporting issue. I can reproduce this issue.

I have merged #71. Please check latest version.

**Comment by yuutayamada** [comment]
Thank you for quick reply and merging!

**Comment by syohex** [comment]
And I fixed ANSI color escape sequences issue too at #73. I think error message of `nim` is colored with latest version.

![after](https://cloud.githubusercontent.com/assets/554281/12771251/3a863f9c-ca6b-11e5-81be-79429b13cdff.png)

**Comment by yuutayamada** [comment]
I love that :+1:
