### ISSUE TITLE
rust compile only error

### ISSUE THREAD

**Issue by futurist** [syohex/emacs-quickrun#87]
quickrun `rustc` with `C-u C-u` (compile only) will give below error:

```
-*- mode: compilation; default-directory: "~/Rust/101/" -*-
Comint started at Thu Jan 26 15:30:53

rustc --no-trans --warn-unused-imports  -o /Users/pro/Rust/101/1.out 1.rs
error: Unrecognized option: 'no-trans'.


Comint exited abnormally with code 101 at Thu Jan 26 15:30:53

```

Rust 1.14

**Comment by syohex** [comment]
Its options are too old. I should update its options.

**Comment by futurist** [comment]
Also, the `compile only` buffer is not readonly and without the <kbd>q</kbd> key binding. Should it have one like the run result output buffer?

**Comment by syohex** [comment]
> Also, the compile only buffer is not readonly and without the q key binding. Should it have one like the run result output buffer?

compile only command uses `compilation-start` function however it does not turn on readonly-mode as `M-x compile`. However there are some hooks of it, like `compilation-finish-function`. `compilation-start` is asynchronous function, so quickrun.el cannot change its value temporarily.
